#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

#
# Helper Functions
# http://apple.stackexchange.com/a/96810/7647
#
local brew="echo ; echo 'UPDATING HOMEBREW'; echo ; brew update; brew upgrade; brew cleanup;"
local cask="echo ; echo 'UPDATING CASK'; echo ; brew cask upgrade; "
local pip3="pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip3 install -U -q"
local zshconfig="echo ; echo 'UPDATING ZSH-CONFIG'; echo ; cd ${HOME}/.zsh-config; git pull && git submodule update --init --recursive ;"
sh -c $brew$cask$zshconfig$pip3
